// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWeIdwEe2rS3fMvrbayV0gQeWY9zpnAxo',
    appId: '1:238329653617:web:536ba602de212a66ffaed0',
    messagingSenderId: '238329653617',
    projectId: 'meddly-fbcf7',
    authDomain: 'meddly-fbcf7.firebaseapp.com',
    storageBucket: 'meddly-fbcf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcIwhcdU-mnBGWxBNG0-6TXAG1QFW8Ig',
    appId: '1:238329653617:android:34dbaa555bc066a3ffaed0',
    messagingSenderId: '238329653617',
    projectId: 'meddly-fbcf7',
    storageBucket: 'meddly-fbcf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFd3iQR-qfLhQVrD6B1X8cJVT4InxmoQ',
    appId: '1:238329653617:ios:5e40a158a5098ca8ffaed0',
    messagingSenderId: '238329653617',
    projectId: 'meddly-fbcf7',
    storageBucket: 'meddly-fbcf7.appspot.com',
    iosClientId:
        '238329653617-4kh9u60strvlrhbp56ncsjup4uhh068p.apps.googleusercontent.com',
    iosBundleId: 'com.example.meddly',
  );
}
